### ISSUE TITLE
Getting Items 

### ISSUE THREAD

**Issue by frigtul** [pc-coholic/de.pccoholic.pretix.cashpoint#4]
Hi, 
i'm working on "updating" the app. But the getItem function dosnt seem to work. The Api changed quite a bit, from what i know. For the /cashpoint i use /mark_paid . I cant seem to find a replacement for /items. Do you know any? 
Greetings

**Comment by pc-coholic** [comment]
Oh - how is this repository still only - it should have been archived a long time ago...

The items-endpoint should still exist as before: https://docs.pretix.eu/en/latest/api/resources/items.html#get--api-v1-organizers-(organizer)-events-(event)-items-

What's the exact path that you're calling and what's the error-message you're getting?

**Comment by pc-coholic** [comment]
Also - if you are located in Germany - please do not use this approach for marking things as paid.

With the introduction of the Kassensicherungs-Verordnung there are very strict requirements about using a "Technische Sicherheitseinrichtung" (TSE/Fiscal Element) whenever accepting cash and using technology to provide services. Unless you plan on adding a TSE to this app, using it will be not legal in Germany and could make you liable to very hefty fines as well as back-taxes, reviews, etc.

Please use [pretxPOS](https://pretix.eu/about/en/pos) instead in that case.

**Comment by frigtul** [comment]
Wow thats was a fast responce. I'm using the path "baseURL/api/v1/organizers/" + organizer + "/events/" + event + "/items/"

Error Message: Error - Getting Items
Something went wrong getting the items

**Comment by pc-coholic** [comment]
Well, seems like past me built some excellent code™ that ding't care much for properly exposing the real issues and stacktraces...

Perhaps try adding an `e.printStackTrace()` in the `catch`-block of https://github.com/pc-coholic/de.pccoholic.pretix.cashpoint/blob/085eca49e58c9084b1d8358c5f17f9f68c4f7b3c/src/de/pccoholic/pretix/cashpoint/CashpointActivity.java#L415


That should give you a better idea what is failing.

If I were to guess, it's probably something with the handling of the language if there is only a single language enabled in the shop...

**Comment by frigtul** [comment]
Thanks, language handeling seems to be the problem. The language shortcodes are based on? What would be the shortcode for German Formal?

**Comment by pc-coholic** [comment]
German Formal should be `de`, Geman informal `de_Informal`

If you have an active pretix backend session, you can also access the items-endpoint in your webbrowser and just have a look at the returned JSON.

**Comment by frigtul** [comment]
Fantastic. That helps a lot. Thanks for the incredibly fast replies. Have a awesome weekend!.
